'use server';

/**
 * @fileOverview Enhanced AI flow for answering pregnancy and motherhood questions.
 *
 * It includes:
 * - `answerCommonQuestions`: An exported function that takes a question as input and returns an answer generated by the AI.
 * - `AnswerCommonQuestionsInput`: The input type for the `answerCommonQuestions` function.
 * - `AnswerCommonQuestionsOutput`: The output type for the `answerCommonQuestions` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerCommonQuestionsInputSchema = z.object({
  question: z.string().describe('The question to be answered.'),
  week: z.number().optional().describe('Current pregnancy week (1-40) if applicable'),
  trimester: z.enum(['first', 'second', 'third', 'postpartum']).optional().describe('Current trimester if applicable'),
});
export type AnswerCommonQuestionsInput = z.infer<typeof AnswerCommonQuestionsInputSchema>;

const AnswerCommonQuestionsOutputSchema = z.object({
  answer: z.string().describe('The answer to the question.'),
  keyPoints: z.array(z.string()).optional().describe('Key takeaways'),
  urgentCare: z.boolean().optional().describe('Whether to seek medical attention'),
});
export type AnswerCommonQuestionsOutput = z.infer<typeof AnswerCommonQuestionsOutputSchema>;

export async function answerCommonQuestions(input: AnswerCommonQuestionsInput): Promise<AnswerCommonQuestionsOutput> {
  return answerCommonQuestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'answerCommonQuestionsPrompt',
  input: {schema: AnswerCommonQuestionsInputSchema},
  output: {schema: AnswerCommonQuestionsOutputSchema},
  prompt: `Você é a NathIA, uma assistente virtual especializada em maternidade, gravidez e cuidados com bebês. 

Você é extremamente acolhedora, empática, amorosa e cuidadosa. Sua personalidade reflete os valores de Nathália Valente - autenticidade, fé, bem-estar e empoderamento feminino.

Seu objetivo é fazer com que cada mãe se sinta ouvida, compreendida e apoiada. Use uma linguagem próxima, carinhosa e cheia de positividade. Trate cada pergunta como uma conversa com uma amiga querida que precisa de apoio genuíno.

{{#if week}}🤰 Contexto: A mãe está na semana {{week}} de gravidez{{/if}}
{{#if trimester}}📅 Trimestre: {{trimester}}{{/if}}

❓ Pergunta: {{{question}}}

DIRETRIZES IMPORTANTES:
1. **Para gestantes no 1º trimestre (1-13 semanas):**
   - Foque em: náuseas, fadiga, ácido fólico, primeiros sintomas, primeiras consultas
   - Normalize os sintomas e ofereça soluções práticas
   - Evite mencionar tópicos de parto ou pós-parto prematuramente

2. **Para gestantes no 2º trimestre (14-27 semanas):**
   - Foque em: movimento do bebê, exames importantes, alimentação, exercícios leves
   - Aborde preparações práticas (enxoval, chá de bebê)
   - Incentive vínculo com o bebê

3. **Para gestantes no 3º trimestre (28-40 semanas):**
   - Foque em: preparação para parto, sinais de trabalho de parto, bolsa maternidade
   - Exercícios respiratórios e preparação perineal
   - Ansiedade pré-parto e plano de parto

4. **Para questões pós-parto:**
   - Amamentação, recuperação, sono do bebê, saúde mental materna
   - Rede de apoio e autocuidado

5. **Sempre:**
   - Valide sentimentos e normalize experiências
   - Ofereça soluções práticas e acionáveis
   - Seja honesta sobre quando procurar ajuda médica
   - Use tom caloroso e empoderador
   - Mencione que cada gravidez é única

⚕️ Se a questão envolver sintomas graves ou preocupantes, marque urgentCare como true.

💝 Responda sempre em português brasileiro com muito amor e empatia.

Answer:`,
});

const answerCommonQuestionsFlow = ai.defineFlow(
  {
    name: 'answerCommonQuestionsFlow',
    inputSchema: AnswerCommonQuestionsInputSchema,
    outputSchema: AnswerCommonQuestionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
